# Generated by Django 5.0.8 on 2024-10-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('signature_r', models.CharField(max_length=256)),
                ('signature_s', models.CharField(max_length=256)),
                ('public_key_x', models.CharField(max_length=256)),
                ('public_key_y', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='keypair',
            name='private_key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='public_key_x',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='public_key_y',
            field=models.CharField(max_length=256),
        ),
    ]
