# Generated by Django 5.0.8 on 2025-05-11 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signatures', '0003_delete_signeddocument_alter_keypair_private_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('GEN', 'Key Generation'), ('SIGN', 'Message Signing'), ('VER', 'Signature Verification')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('public_key_x', models.CharField(max_length=255)),
                ('public_key_y', models.CharField(max_length=255)),
                ('signature_r', models.CharField(max_length=255)),
                ('signature_s', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verification_result', models.BooleanField()),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('signature_r', models.CharField(max_length=255)),
                ('signature_s', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('key_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_signatures.keypair')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
