# Generated by Django 5.0.8 on 2025-05-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signatures', '0004_useractivity_verificationlog_signaturerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signaturerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificationlog',
            options={},
        ),
    ]
