# Generated by Django 5.0.8 on 2025-05-11 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signatures', '0005_alter_signaturerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
