# Generated by Django 5.0.8 on 2025-05-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_signatures', '0007_auditlog_signaturestats_documentmetadata_and_more'),
    ]

    operations = [
    ]
